from mcp.server.fastmcp import FastMCP

from src.tools.knime.executor import KNIMEExecutor
from src.tools.knime.config import build_knime_config


def register_knime_tools(mcp: FastMCP, raw_config: dict):
    knime_cfg = build_knime_config(raw_config.get("knime", {}))
    executor = KNIMEExecutor(knime_cfg)

    @mcp.tool(
        name="knime_execute_workflow",
        description="Execute a KNIME workflow headless. "
                    "Exit code 0 = success, 4 = execution error. "
                    "Optionally pass workflow variables as key-value pairs.",
    )
    async def knime_execute_workflow(
        workflow_dir: str,
        variables: dict[str, str] | None = None,
        timeout: int = 600,
    ) -> dict:
        """Run a KNIME workflow in batch mode.

        Args:
            workflow_dir: Relative path from workspace root to workflow folder
            variables: Optional workflow variables as key-value pairs
            timeout: Maximum execution time in seconds (default 600)
        """
        result = await executor.execute(workflow_dir, variables, timeout)
        return result.model_dump()

    @mcp.tool(
        name="knime_list_workflows",
        description="List all KNIME workflows in the configured workspace. "
                    "Scans subdirectories for workflow.knime files.",
    )
    async def knime_list_workflows() -> list[dict]:
        """Get all available KNIME workflows."""
        return await executor.list_workflows()

    @mcp.tool(
        name="knime_read_output_table",
        description="Read a CSV output table generated by a KNIME workflow. "
                    "Returns rows as a list of dicts (max 100 rows).",
    )
    async def knime_read_output_table(
        output_path: str,
        max_rows: int = 100,
    ) -> list[dict]:
        """Read output CSV from a KNIME workflow.

        Args:
            output_path: Relative path from workspace to CSV file
            max_rows: Maximum number of rows to return (default 100)
        """
        return await executor.read_output_table(output_path, max_rows)

    @mcp.tool(
        name="knime_get_workflow_status",
        description="Check if a KNIME workflow exists in the workspace "
                    "and return its metadata.",
    )
    async def knime_get_workflow_status(
        workflow_dir: str,
    ) -> dict:
        """Check workflow existence and metadata.

        Args:
            workflow_dir: Relative path to workflow folder
        """
        return await executor.get_workflow_status(workflow_dir)
